sudo: false
dist: trusty
language: c

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc dc -y

script:
  - export FILE_NAME=AVR-ETHERBOOT-$TRAVIS_BRANCH-All-HEX.zip
  - cd device_002
  - make < make.input
  - zip $FILE_NAME device_002.hex device_002.eep
  - ls
  
deploy:
  skip_cleanup: true
  provider: releases
  api-key:
    secure: $GH_TOKEN
  file: 
    - $FILE_NAME
  on:
    tags: true

notifications:
  email:
    - c-n-i@web.de
