language: c

before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc

script:
  - export FILE_NAME=AVR-ETHERBOOT-$TRAVIS_BRANCH-All-HEX.zip
  - echo $FILE_NAME
  - mkdir fw_bootloader
  - cd device_002
  - make clean
  - ls
  - make -mmcu=atmega64 -dM -E "foo.c"
  - cp device_002.hex ../fw_bootloader
  - cp device_002.eep ../fw_bootloader
  - cd ../fw_bootloader
  - ls
  - zip $FILE_NAME device_002.hex device_002.eep
  
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: 
    - $FILE_NAME
  on:
    tags: true

notifications:
  email:
    - c-n-i@web.de
